# Generated by Django 4.1.7 on 2023-03-03 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("alignment_api", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Token",
            new_name="SourceToken",
        ),
        migrations.RemoveField(
            model_name="link",
            name="sourceTokens",
        ),
        migrations.RemoveField(
            model_name="link",
            name="targetTokens",
        ),
        migrations.AddField(
            model_name="link",
            name="source_tokens",
            field=models.ManyToManyField(
                related_name="source_tokens", to="alignment_api.sourcetoken"
            ),
        ),
        migrations.CreateModel(
            name="TargetToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_id", models.CharField(max_length=15)),
                ("text", models.CharField(max_length=150)),
                (
                    "resource",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="alignment_api.resource",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="link",
            name="target_tokens",
            field=models.ManyToManyField(
                related_name="target_tokens", to="alignment_api.targettoken"
            ),
        ),
    ]
