# Generated by Django 4.1.7 on 2023-03-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "alignment_api",
            "0002_rename_token_sourcetoken_remove_link_sourcetokens_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="source_tokens",
            field=models.ManyToManyField(
                related_name="links", to="alignment_api.sourcetoken"
            ),
        ),
        migrations.AlterField(
            model_name="link",
            name="target_tokens",
            field=models.ManyToManyField(
                related_name="links", to="alignment_api.targettoken"
            ),
        ),
    ]
