# Generated by Django 4.1.7 on 2023-03-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alignment_api", "0004_auto_20230306_1456"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourcetoken",
            name="gloss",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="sourcetoken",
            name="text",
            field=models.CharField(max_length=150, null=True),
        ),
    ]
