# Generated by Django 4.1.7 on 2023-03-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alignment_api", "0005_sourcetoken_gloss_alter_sourcetoken_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourcetoken",
            name="lemma",
            field=models.CharField(max_length=150, null=True),
        ),
    ]
