# Generated by Django 4.1.7 on 2023-03-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alignment_api", "0006_sourcetoken_lemma"),
    ]

    operations = [
        migrations.AddField(
            model_name="targettoken",
            name="is_punc",
            field=models.BooleanField(null=True),
        ),
    ]
