# Generated by Django 4.1.7 on 2023-03-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alignment_api", "0007_targettoken_is_punc"),
    ]

    operations = [
        migrations.AddField(
            model_name="alignment",
            name="type",
            field=models.CharField(max_length=150, null=True),
        ),
    ]
