# Generated by Django 4.2.1 on 2023-06-02 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("alignment_api", "0009_subject_mediaasset_sourcetoken_subjects"),
    ]

    operations = [
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "license_id",
                    models.CharField(
                        help_text="Unique identifier for a license statement.",
                        max_length=256,
                        unique=True,
                    ),
                ),
                (
                    "license_url",
                    models.URLField(
                        blank=True,
                        help_text="The URL for a full license statement supporting an identifier.",
                    ),
                ),
                (
                    "attribution",
                    models.BooleanField(help_text="Does this license require attribution?"),
                ),
                (
                    "sharealike",
                    models.BooleanField(
                        help_text=(
                            "Does this license require distributing your contributions under the"
                            " same license as the original?"
                        )
                    ),
                ),
                (
                    "noderivs",
                    models.BooleanField(
                        help_text=(
                            "Does this license restrict you from distributing modified material?"
                        )
                    ),
                ),
                (
                    "noncommercial",
                    models.BooleanField(
                        help_text=(
                            "Does this license restrict you from using this material for commercial"
                            " purposes?"
                        )
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="copyright",
            field=models.CharField(
                blank=True,
                help_text=(
                    "The copyright statement provided by the publisher. Leave blank for public"
                    " domain licenses."
                ),
                max_length=256,
            ),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="creator",
            field=models.CharField(
                blank=True,
                help_text=(
                    "The entity responsible for making this resource. Examples include a person, an"
                    " organization, or a service. Typically, the name of a Creator should be used"
                    " to indicate the entity."
                ),
                max_length=256,
            ),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="publisher",
            field=models.CharField(
                blank=True,
                help_text=(
                    "The entity responsible for making this resource available. Examples include a"
                    " person, an organization, or a service. Typically, the name of a Publisher"
                    " should be used to indicate the entity."
                ),
                max_length=256,
            ),
        ),
        migrations.AlterField(
            model_name="mediaasset",
            name="asset_type",
            field=models.SlugField(
                choices=[
                    ("ART", "Art"),
                    ("ARTICLE", "Article"),
                    ("CHART", "Chart"),
                    ("MAP", "Map"),
                    ("PHOTO", "Photo"),
                    ("OTHER", "Other"),
                ],
                help_text="The type of media.",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="mediaasset",
            name="dam_id",
            field=models.SlugField(
                help_text="Identifier from backend storage for this asset.",
                max_length=128,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="mediaasset",
            name="description",
            field=models.TextField(
                blank=True, help_text="Publisher's English description for this asset."
            ),
        ),
        migrations.AlterField(
            model_name="mediaasset",
            name="media_asset_id",
            field=models.SlugField(
                help_text=(
                    "Unique identifier for this asset. Best practice is to use the publisher's"
                    " value, if available."
                ),
                max_length=256,
                unique=True,
            ),
        ),
        migrations.RemoveField(
            model_name="mediaasset",
            name="subject",
        ),
        migrations.AlterField(
            model_name="mediaasset",
            name="subtitle",
            field=models.CharField(
                blank=True, help_text="Publisher's English subtitle for this asset.", max_length=256
            ),
        ),
        migrations.AlterField(
            model_name="mediaasset",
            name="title",
            field=models.CharField(
                blank=True, help_text="Publisher's English title for this asset.", max_length=256
            ),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="license",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="alignment_api.license",
            ),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="subject",
            field=models.ManyToManyField(
                help_text="The primary subject that is illustrated by this item.",
                to="alignment_api.subject",
            ),
        ),
    ]
